### ISSUE TITLE
Note!!!

### ISSUE THREAD

**Issue by rafa19** [IainMcManus/FlagAndCountryData#1]
Hello,
The flag with regards to Nagorno-Karabakh you have set here doesn't mirror reality. Nagorno-Karabakh, where belongs to the Republic of Azerbaijan had been occupied by Armenian terrorists.
Please remove this flag.

**Comment by IainMcManus** [comment]
The image currently used by the flag is the one used on a variety of established sources (eg. wikipedia) and, as indicated, is provided by a third party. It is important that the data here is consistent with those established sources. I regret therefore that I cannot remove the flag at this time. You are however welcome to fork the repository and make whatever modifications to it you feel are appopriate.
